config/routes.rb
Blog::Application.routes.draw do
  resources :bloggers

  devise_for :users
  get "welcome/index"

   root 'welcome#index'

    resources :bloggers do
     resources :posts do
      resources :comments
     end
    end

  

end

app/models/blogger.rb
class Blogger < ActiveRecord::Base
  belongs_to :user
  has_many :posts
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
	validates :title, presence: true,
	length: { minimum: 5 }
	has_many :comments, dependent: :destroy
	belongs_to :blogger
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_one :blogger
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/bloggers_controller.rb
class BloggersController < ApplicationController
  before_action :set_blogger, only: [:show, :edit, :update, :destroy]

  # GET /bloggers
  # GET /bloggers.json
  def index
    @bloggers = Blogger.all
  end

  # GET /bloggers/1
  # GET /bloggers/1.json
  def show
  end

  # GET /bloggers/new
  def new
    @blogger = Blogger.new
  end

  # GET /bloggers/1/edit
  def edit
  end

  # POST /bloggers
  # POST /bloggers.json
  def create
    @blogger = Blogger.new(blogger_params)

    respond_to do |format|
      if @blogger.save
        format.html { redirect_to @blogger, notice: 'Blogger was successfully created.' }
        format.json { render action: 'show', status: :created, location: @blogger }
      else
        format.html { render action: 'new' }
        format.json { render json: @blogger.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bloggers/1
  # PATCH/PUT /bloggers/1.json
  def update
    respond_to do |format|
      if @blogger.update(blogger_params)
        format.html { redirect_to @blogger, notice: 'Blogger was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @blogger.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bloggers/1
  # DELETE /bloggers/1.json
  def destroy
    @blogger.destroy
    respond_to do |format|
      format.html { redirect_to bloggers_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blogger
      @blogger = Blogger.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blogger_params
      params.require(:blogger).permit(:title, :user_id)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(params[:comment].permit(:commenter, :body))
    redirect_to post_path(@post)
  end
  def destroy
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    @comment.destroy
    redirect_to post_path(@post)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

	before_filter :authenticate_user!

	def index
		@posts = current_user.blogger.posts
	end
	
	def new
		@post = Post.new
	end

	def create
		@post = Post.new(post_params)

		if @post.save
			redirect_to @post
		else
			render 'new'
		end
	end

	def destroy
  		@post = Post.find(params[:id])
  		@post.destroy
 
		redirect_to posts_path
	end

	def show
		@post = Post.find(params[:id])
	end

	def edit
		@post = Post.find(params[:id])
	end

	def update
  		@post = Post.find(params[:id])
 
		if @post.update(params[:post].permit(:title, :text))
    		redirect_to @post
  		else
    		render 'edit'
  		end
	end

	private
		def post_params
			params.require(:post).permit(:title, :text)
		end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  	if user_signed_in?
  		if current_user.blogger.nil?
  			Blogger.create(:user_id=>current_user.id, :title=>"Blog de "+current_user.email)
  		end
  	end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bloggers_helper.rb
module BloggersHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/bloggers/_form.html.erb
<%= form_for(@blogger) do |f| %>
  <% if @blogger.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@blogger.errors.count, "error") %> prohibited this blogger from being saved:</h2>

      <ul>
      <% @blogger.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :user %><br>
    <%= f.text_field :user %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/bloggers/edit.html.erb
<h1>Editing blogger</h1>

<%= render 'form' %>

<%= link_to 'Show', @blogger %> |
<%= link_to 'Back', bloggers_path %>

app/views/bloggers/index.html.erb
<h1>Listing bloggers</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>User</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @bloggers.each do |blogger| %>
      <tr>
        <td><%= blogger.title %></td>
        <td><%= blogger.user %></td>
        <td><%= link_to 'Show', blogger %></td>
        <td><%= link_to 'Edit', edit_blogger_path(blogger) %></td>
        <td><%= link_to 'Destroy', blogger, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Blogger', new_blogger_path %>

app/views/bloggers/new.html.erb
<h1>New blogger</h1>

<%= render 'form' %>

<%= link_to 'Back', bloggers_path %>

app/views/bloggers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @blogger.title %>
</p>

<p>
  <strong>User:</strong>
  <%= @blogger.user %>
</p>

<%= link_to 'Edit', edit_blogger_path(@blogger) %> |
<%= link_to 'Back', bloggers_path %>

app/views/comments/_comment.html.erb
<table class="table">
<th></th>
<tr>
<p class="color-white">
  <strong>Bloguero:</strong>
  <%= comment.commenter %>
</p>
 
<p class="color-white">
  <strong>Comentario:</strong>
  <%= comment.body %>
</p>
<p>
  <%= link_to 'Eliminar Comentario', [comment.post, comment],
               method: :delete,
               data: { confirm: '¿Estás seguro?' } %>
</p>
<tr>
</table>

app/views/comments/_form.html.erb
<h2 class="color-white">Agregar Comentario: </h2>
<%= form_for([@post, @post.comments.build]) do |f| %>
  <p class="color-white">
    <%= f.label "Bloguero" %><br />
    <%= f.text_field :commenter, :class => "form-control" %>
  </p>
  <p class="color-white">
    <%= f.label "Comentario" %><br />
    <%= f.text_area :body, :class => "form-control" %>
  </p>
  <p>
  <div class="span6">
    <%= submit_tag "Crear Comentario", :class => "btn btn-primary btn-claudia"%>
    </div>
  </p>
<% end %>

app/views/layouts/_user_header.html.erb
<ul class="nav nav-pills pull-right">
  <% if user_signed_in? %>
    <li><%= link_to "Salir", destroy_user_session_path, :method => :delete, :class => "color-blue" %></li>
  <% else %>
    <li ><%= link_to "Ingresar", new_user_session_path,:class => "color-blue" %></li>
    <li><%= link_to "Registrarse", new_user_registration_path,:class => "color-blue" %></li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog de Cloooska</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">
  <div class="masthead">
    <%= render 'layouts/user_header' %>
    <h2 class="muted"><%= link_to "El Blog de Cloooska", root_path,:class => "color-blue" %></h2>
    <h5 class="color-white">Un entretenido lugar para comentar</h5>
  </div>
  <hr />
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
  <%= yield %>
</div>
<div class="color-white">
:D #Rhodium2013 & Cloooska
</div>
</body>
</html>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
	
	 <% if @post.errors.any? %>
  	<div id="errorExplanation">
    	<h2><%= pluralize(@post.errors.count, "error") %> :prohibited this post from being saved:</h2>
    <ul>
    <% @post.errors.full_messages.each do |msg| %>
  	  <li><%= msg %></li>
    <% end %>
    </ul>
	</div>
	<% end %>

	<p class="color-white">
		<%= f.label "Título" %><br>
		<%= f.text_field :title, :class => "form-control" %>
	</p>
	<p class="color-white">
		<%= f.label "Post" %><br>
		<%= f.text_area :text, :class => "form-control" %>
	</p>
	<div class="row-fluid">
	<div class="span6">
		<%= submit_tag "Crear Post", :class => "btn btn-primary btn-claudia"%>
	</div>
	</p>
	<% end %>
	<div class="span6">
        <%= link_to "Mis Posts", posts_path, :class => "btn btn-primary btn-claudia" %>
    </div>
    </div>

<br>

app/views/posts/edit.html.erb
<h1 class="color-white">Editar Comentario</h1>
 
<%= render 'form' %>

app/views/posts/index.html.erb
<div class="color-white">
<h1>Mis Posteos</h1>
<table class="table">
	<tr>
		<th>Título</th>
		<th>Post</th>
		<th></th>
		<th></th>
    	<th></th>
	</tr>
	<% @posts.each do |post| %>
	<tr>
		<td><%= post.title %></td>
		<td><%= post.text %></td>
		
    	<td>
    		<div class="span6">
        	<%= link_to "Mostrar", blogger_post_path(post), :class => "btn btn-primary btn-claudia" %>
			</div>
    	</td>
    	<td>
    		<div class="span6">
        	<%= link_to "Editar", edit_post_path(post), :class => "btn btn-primary btn-claudia" %>
			</div>
    	</td>
    	<td>
    		<div class="span6">
        	<%= link_to "Eliminar", post_path(post), :class => "btn btn-primary btn-claudia", method: :delete, data: { confirm: '¿Estás seguro?' } %>
			</div>
    	</td>
	</tr>
	<% end %>
</table>
<div class="span6">
        <%= link_to "Nuevo Post", new_blogger_post_path, :class => "btn btn-primary btn-claudia" %>
        <br>
        <br>
</div>
</div>

app/views/posts/new.html.erb
<div class="btn-claudia">
<h2 clsass="color-white">Nuevo Post</h2>
</div>
 
<%= render 'form' %>

app/views/posts/show.html.erb
<div class="border-form-div jumbotron box-claudia3">
<p class="color-white">
	<strong>Título:</strong>
	<%= @post.title %>
</p>

<p class="color-white">
	<strong>Texto:</strong>
	<%= @post.text %>
</p>
</div>


<h2 class="color-white">Comentarios</h2>
<%= render @post.comments %>

<%= render "comments/form" %>

<div class="span6">
        <%= link_to "Mis Posts", posts_path, :class => "btn btn-primary btn-claudia" %>
</div>
<br>

app/views/welcome/index.html.erb
<div class="jumbotron box-claudia2">
<%= csrf_meta_tag %>
  <% if user_signed_in? %>
    <h1>Bienvenido, buen usuario!</h1>
    <p class="lead">
      Acabas de logearte!  Pero en caso de que quieras escapar de inmediato, haz click en el botón rojo :D
    </p>
    
    <% unless current_user.blogger.nil? %>
    <%= link_to "Entrar al Blog", blogger_posts_path(current_user.blogger), :class => "btn btn-primary btn-claudia2" %>
    <%end%>
    <%= link_to "Salir", destroy_user_session_path, :method => :delete, :class => 'btn btn-large btn-danger' %>
  


  <% else %>
    <h1>Bienvenido al Blog de Cloooska!</h1>
    <p class="lead">
      Debes ingresar o registrarte antes de leer este blog super secreto!
    </p>
    <div class="row-fluid">
      <div class="span6">
        <%= link_to "Ingresar", new_user_session_path, :class => "btn btn-primary btn-claudia2" %>
      </div>
      <div class="span6">
        <%= link_to "Registrarse", new_user_registration_path, :class => "btn btn-primary btn-claudia2" %>
      </div>
    </div>
  <% end %>
</div>